import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Container, Heading, Stack, Text } from '@chakra-ui/react'

const Counter = () => {
  const [count, setCount] = useState(0)

  return (
    <Container>
      <Heading>{count}</Heading>

      <Stack spacing={4} direction="row">
        <Button onClick={_ => setCount(count - 1)}>-</Button>
        <Button onClick={_ => setCount(count + 1)}>+</Button>
      </Stack>
    </Container>
  )
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Idk something about lights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Counter />
      </main>
    </div>
  )
}

export default Home
